# =============================================================================
# render/renderer.py  —  EcoForge "World Balance Architects"
# Elegant pixel-art renderer using pygame-ce + Pillow
#
# Features:
#   • Pixel-art terrain tiles (48×48, generated by Pillow)
#   • Animated water (2-frame oscillation)
#   • Day/Night cycle tint (every 20 turns)
#   • FloatingText  — "+Food", "+O₂", etc. rising and fading
#   • CameraShake   — triggered on critical events
#   • Cell highlight — glowing border on last-played tile
#   • Particle burst — on harvest / plant actions
#   • Pulsing meter  — flashes red when any resource < 20
#   • AI "thinking"  — animated dot while agent computes
#   • Game-over overlay with winner banner
#   • Scanline + vignette post-FX for retro feel
# =============================================================================

from __future__ import annotations
import math, os, sys
import pygame
from PIL import Image as PILImage

try:
    from .animations import WaterAnimator, FloatingText, Particle, CameraShake, AmbientOrb
except ImportError:
    # Fallback for direct script execution outside package context.
    from animations import WaterAnimator, FloatingText, Particle, CameraShake, AmbientOrb

# ── PATH SETUP ────────────────────────────────────────────────────────────────
_HERE       = os.path.dirname(os.path.abspath(__file__))
_ROOT       = os.path.dirname(_HERE)
ASSETS_DIR  = os.path.join(_ROOT, "assets", "tiles")

# ── IMPORT CONFIG (fall back to sensible defaults) ────────────────────────────
try:
    sys.path.insert(0, _ROOT)
    from config import (
        GRID_WIDTH, GRID_HEIGHT, TILE_SIZE,
        SCREEN_WIDTH, SCREEN_HEIGHT, MAX_TURNS,
        TERRAIN_LAND, TERRAIN_RIVER, TERRAIN_FARM,
        TERRAIN_FOREST, TERRAIN_RESERVOIR, TERRAIN_SOLAR,
        AGENT_A, AGENT_B,
        AGENT_A_COLOR, AGENT_B_COLOR,
        STABILITY_HIGH, STABILITY_MODERATE, STABILITY_LOW,
        UI_PANEL_X, UI_PANEL_WIDTH,
    )
except ImportError:
    # Sensible defaults so the renderer can be tested standalone
    GRID_WIDTH, GRID_HEIGHT, TILE_SIZE = 25, 18, 48
    SCREEN_WIDTH, SCREEN_HEIGHT        = 1480, 900
    MAX_TURNS                          = 150
    TERRAIN_LAND, TERRAIN_RIVER        = "land",    "river"
    TERRAIN_FARM, TERRAIN_FOREST       = "farm",    "forest"
    TERRAIN_RESERVOIR, TERRAIN_SOLAR   = "reservoir","solar_plant"
    AGENT_A, AGENT_B                   = "A", "B"
    AGENT_A_COLOR, AGENT_B_COLOR       = (220,80,60),(60,140,220)
    STABILITY_HIGH, STABILITY_MODERATE = 0.75, 0.50
    STABILITY_LOW                      = 0.25
    UI_PANEL_X   = GRID_WIDTH * TILE_SIZE
    UI_PANEL_WIDTH = SCREEN_WIDTH - UI_PANEL_X

GRID_PX_W = GRID_WIDTH  * TILE_SIZE
GRID_PX_H = GRID_HEIGHT * TILE_SIZE

# ── COLOUR PALETTE ────────────────────────────────────────────────────────────
C_BG          = ( 12,  14,  22)   # deep space background
C_PANEL       = ( 18,  22,  36)   # UI panel
C_PANEL_DARK  = ( 12,  15,  26)   # panel header
C_BORDER      = ( 40,  48,  72)   # panel border
C_TEXT        = (200, 210, 230)   # primary text
C_TEXT_DIM    = (110, 125, 160)   # secondary text
C_TEXT_BRIGHT = (240, 245, 255)   # heading text
C_ACCENT      = ( 80, 180, 255)   # blue accent
C_GOOD        = ( 80, 220, 130)   # green — healthy
C_WARN        = (220, 200,  60)   # yellow — caution
C_DANGER      = (220,  70,  60)   # red — critical
C_GOLD        = (255, 210,  60)   # gold — score / win

METER_COLORS = {
    "water":   ( 60, 160, 255),
    "food":    (100, 220,  80),
    "oxygen":  (100, 230, 210),
    "temp":    (255, 140,  60),
}

DAY_TINTS = [
    (255, 255, 255, 0  ),   # day      — no tint
    (255, 190, 120, 45 ),   # dusk     — warm amber
    ( 40,  50, 110, 70 ),   # night    — deep blue
    (180, 130, 200, 35 ),   # dawn     — soft violet
]


# =============================================================================
# ASSET LOADER
# =============================================================================

def _pil_to_pygame(pil_img: PILImage.Image) -> pygame.Surface:
    """Convert a PIL RGBA image to a pygame Surface."""
    raw  = pil_img.convert("RGBA").tobytes()
    surf = pygame.image.frombytes(raw, pil_img.size, "RGBA").convert_alpha()
    return surf


def _load_tile(name: str) -> pygame.Surface | None:
    path = os.path.join(ASSETS_DIR, f"{name}.png")
    if not os.path.exists(path):
        return None
    pil = PILImage.open(path)
    return _pil_to_pygame(pil)


def _load_preview_sheet_tile(sheet_name: str, index: int) -> pygame.Surface | None:
    """Crop a 48x48 tile from a preview sheet when the standalone tile is missing."""
    path = os.path.join(ASSETS_DIR, f"{sheet_name}.png")
    if not os.path.exists(path):
        return None

    pil = PILImage.open(path).convert("RGBA")
    tile_size = 48
    left = index * tile_size
    box = (left, 0, left + tile_size, tile_size)
    if box[2] > pil.width or box[3] > pil.height:
        return None
    return _pil_to_pygame(pil.crop(box))


def _scale_tile(surf: pygame.Surface, size: int) -> pygame.Surface:
    """Nearest-neighbour upscale — keeps pixel-art crisp."""
    if surf.get_width() == size and surf.get_height() == size:
        return surf
    return pygame.transform.scale(surf, (size, size))


# =============================================================================
# MAIN RENDERER
# =============================================================================

class Renderer:
    """
    Drop-in replacement for the original Renderer class.
    Call  renderer.draw(world)  once per frame.
    For game-over:  renderer.draw_game_over(world, winner)
    To spawn FX:    renderer.add_float(text, col, row, color)
                    renderer.add_particles(col, row, color, count)
                    renderer.camera_shake.trigger()
    """

    # ── INIT ─────────────────────────────────────────────────────────────────

    def __init__(self, screen: pygame.Surface):
        self.screen       = screen
        self._water       = WaterAnimator()
        self.camera_shake = CameraShake()
        self._floats:    list[FloatingText] = []
        self._particles: list[Particle]     = []
        self._last_action                   = None   # (row, col, age)
        self._thinking_agent: str | None    = None
        self._ticks = 0
        self._ambient_orbs: list[AmbientOrb] = []

        self._load_fonts()
        self._load_tiles()
        self._build_static_surfaces()
        self._build_ambient_layer()

    def _load_fonts(self):
        pygame.font.init()
        # Try to load a pixel font; fall back to built-in
        pixel_font_path = os.path.join(_ROOT, "assets", "fonts", "Pixel Game.otf")
        try:
            self.font_xs  = pygame.font.Font(pixel_font_path, 10)
            self.font_sm  = pygame.font.Font(pixel_font_path, 13)
            self.font_md  = pygame.font.Font(pixel_font_path, 16)
            self.font_lg  = pygame.font.Font(pixel_font_path, 22)
            self.font_xl  = pygame.font.Font(pixel_font_path, 30)
            print(f"[FONT] Loaded Pixel Game.otf from: {pixel_font_path}")
        except Exception as e:
            print(f"[FONT] Failed to load {pixel_font_path}: {e}")
            print(f"[FONT] Fallback to Consolas,monospace")
            self.font_xs  = pygame.font.SysFont("Consolas,monospace", 11)
            self.font_sm  = pygame.font.SysFont("Consolas,monospace", 13)
            self.font_md  = pygame.font.SysFont("Consolas,monospace", 15)
            self.font_lg  = pygame.font.SysFont("Consolas,monospace", 20, bold=True)
            self.font_xl  = pygame.font.SysFont("Consolas,monospace", 28, bold=True)

    def _load_tiles(self):
        """Load pixel-art tile PNGs (generated by Pillow) and scale to TILE_SIZE."""
        T = TILE_SIZE
        def L(name): s = _load_tile(name); return _scale_tile(s, T) if s else None

        self._tile: dict[str, pygame.Surface | None] = {
            TERRAIN_LAND:       L("land"),
            TERRAIN_RIVER:      L("river_1"),     # frame 0
            "river_2":          L("river_2") or _load_preview_sheet_tile("tile_preview_sheet", 2),  # frame 1
            TERRAIN_FARM:       L("farm"),
            TERRAIN_FOREST:     L("forest"),
            TERRAIN_RESERVOIR:  L("reservoir"),
            TERRAIN_SOLAR:      L("solar_plant"),
            # overlays
            "farm_s1":          L("farm_stage_1"),
            "farm_s2":          L("farm_stage_2"),
            "farm_s3":          L("farm_stage_3"),
            "forest_m2":        L("forest_mat_2"),
            "forest_m3":        L("forest_mat_3"),
            "highlight":        L("highlight"),
            "highlight_green":  L("highlight_green"),
            "owner_a":          L("owner_a_tint"),
            "owner_b":          L("owner_b_tint"),
        }

        # Generate fallback coloured rects for any missing tiles
        FALLBACK_COLORS = {
            TERRAIN_LAND:      (104, 168,  72),
            TERRAIN_RIVER:     ( 40, 100, 180),
            TERRAIN_FARM:      (180, 130,  50),
            TERRAIN_FOREST:    ( 40, 100,  40),
            TERRAIN_RESERVOIR: ( 60, 100, 160),
            TERRAIN_SOLAR:     (180, 180,  60),
        }
        for key, color in FALLBACK_COLORS.items():
            if self._tile.get(key) is None:
                surf = pygame.Surface((T, T))
                surf.fill(color)
                self._tile[key] = surf

    def _build_static_surfaces(self):
        """Pre-render surfaces that don't change each frame."""
        T  = TILE_SIZE
        PW = UI_PANEL_WIDTH

        # Scanline overlay for the grid area (retro effect)
        self._scanlines = pygame.Surface((GRID_PX_W, GRID_PX_H), pygame.SRCALPHA)
        for y in range(0, GRID_PX_H, 2):
            pygame.draw.line(self._scanlines, (0,0,0,30), (0,y), (GRID_PX_W,y))

        # Vignette overlay for the grid
        self._vignette = pygame.Surface((GRID_PX_W, GRID_PX_H), pygame.SRCALPHA)
        cx, cy = GRID_PX_W // 2, GRID_PX_H // 2
        for r in range(max(cx,cy), 0, -4):
            alpha = max(0, int(80 * (r / max(cx,cy)) - 30))
            # draw rings from outside in
            pygame.draw.ellipse(self._vignette, (0,0,0,alpha),
                                (cx-r, cy-r//2, r*2, r), 4)

        # Owner tint fallbacks (in case PNGs didn't load)
        if self._tile.get("owner_a") is None:
            s = pygame.Surface((T,T), pygame.SRCALPHA)
            s.fill((*AGENT_A_COLOR, 55))
            pygame.draw.rect(s, (*AGENT_A_COLOR, 200), s.get_rect(), 2)
            self._tile["owner_a"] = s
        if self._tile.get("owner_b") is None:
            s = pygame.Surface((T,T), pygame.SRCALPHA)
            s.fill((*AGENT_B_COLOR, 55))
            pygame.draw.rect(s, (*AGENT_B_COLOR, 200), s.get_rect(), 2)
            self._tile["owner_b"] = s

    def _build_ambient_layer(self):
        """Create slow-moving glows that keep the board feeling alive."""
        self._ambient_orbs = [
            AmbientOrb((GRID_PX_W, GRID_PX_H), (80, 180, 255), 42, (0.35, 0.12)),
            AmbientOrb((GRID_PX_W, GRID_PX_H), (80, 220, 130), 34, (-0.22, 0.18)),
            AmbientOrb((GRID_PX_W, GRID_PX_H), (255, 210, 90), 28, (0.18, -0.14)),
        ]

    # ── PUBLIC API ────────────────────────────────────────────────────────────

    def set_last_action(self, row: int, col: int):
        """Call after each agent move to highlight that cell."""
        self._last_action = [row, col, 0]

    def set_thinking(self, agent: str | None):
        """Pass the current agent name while it's computing; None to clear."""
        self._thinking_agent = agent

    def add_float(self, text: str, col: int, row: int,
                  color: tuple = (255, 255, 200)):
        self._floats.append(FloatingText(text, col, row, TILE_SIZE, color))

    def add_particles(self, col: int, row: int, color: tuple, count: int = 8):
        cx = col * TILE_SIZE + TILE_SIZE // 2
        cy = row * TILE_SIZE + TILE_SIZE // 2
        for _ in range(count):
            self._particles.append(Particle((cx, cy), color))

    # ── MAIN DRAW ─────────────────────────────────────────────────────────────

    def draw(self, world):
        """Full frame render. Call once per game-loop iteration."""
        self._ticks += 1
        self._water.update()

        ox, oy = self.camera_shake.offset()

        # Render grid to an off-screen surface, then blit with shake offset
        grid_surf = pygame.Surface((GRID_PX_W, GRID_PX_H))
        grid_surf.fill(C_BG)
        self._draw_tiles(grid_surf, world)
        self._draw_owner_tints(grid_surf, world)
        self._draw_ambient_layer(grid_surf)
        self._draw_grid_lines(grid_surf)
        self._draw_action_highlight(grid_surf)
        self._apply_day_night(grid_surf, world)
        grid_surf.blit(self._scanlines, (0, 0))

        self.screen.fill(C_BG)
        self.screen.blit(grid_surf, (ox, oy))

        # Particles and floats drawn directly on screen (not shaken)
        self._update_and_draw_particles()
        self._update_and_draw_floats()

        self._draw_ui_panel(world)
        self._tick_last_action()

    def draw_game_over(self, world, winner: str):
        """Call instead of draw() on the final frame."""
        self.draw(world)   # draw the final game state underneath
        self._draw_gameover_overlay(world, winner)

    # ── TILE DRAWING ──────────────────────────────────────────────────────────

    def _draw_tiles(self, surf: pygame.Surface, world):
        river_key = "river_2" if self._water.frame else TERRAIN_RIVER
        for r in range(GRID_HEIGHT):
            for c in range(GRID_WIDTH):
                cell    = world.grid[r][c]
                terrain = cell.terrain
                key     = river_key if terrain == TERRAIN_RIVER else terrain
                tile    = self._tile.get(key) or self._tile.get(terrain)
                if tile:
                    surf.blit(tile, (c * TILE_SIZE, r * TILE_SIZE))

                # Stage / maturity overlays
                if terrain == TERRAIN_FARM:
                    s = getattr(cell, "crop_stage", 0)
                    if 1 <= s <= 3:
                        ov = self._tile.get(f"farm_s{s}")
                        if ov:
                            surf.blit(ov, (c * TILE_SIZE, r * TILE_SIZE))
                elif terrain == TERRAIN_FOREST:
                    m = getattr(cell, "forest_maturity", 1)
                    if m >= 2:
                        ov = self._tile.get(f"forest_m{min(m,3)}")
                        if ov:
                            surf.blit(ov, (c * TILE_SIZE, r * TILE_SIZE))

    def _draw_owner_tints(self, surf: pygame.Surface, world):
        for r in range(GRID_HEIGHT):
            for c in range(GRID_WIDTH):
                owner = getattr(world.grid[r][c], "owner", None)
                if owner == AGENT_A:
                    surf.blit(self._tile["owner_a"], (c*TILE_SIZE, r*TILE_SIZE))
                elif owner == AGENT_B:
                    surf.blit(self._tile["owner_b"], (c*TILE_SIZE, r*TILE_SIZE))

    def _draw_grid_lines(self, surf: pygame.Surface):
        color = (0, 0, 0, 50)
        # Draw as a single surface for speed
        line_surf = pygame.Surface((GRID_PX_W, GRID_PX_H), pygame.SRCALPHA)
        for c in range(GRID_WIDTH + 1):
            x = c * TILE_SIZE
            pygame.draw.line(line_surf, (0,0,0,60), (x,0), (x, GRID_PX_H))
        for r in range(GRID_HEIGHT + 1):
            y = r * TILE_SIZE
            pygame.draw.line(line_surf, (0,0,0,60), (0,y), (GRID_PX_W, y))
        surf.blit(line_surf, (0,0))

    def _draw_action_highlight(self, surf: pygame.Surface):
        if self._last_action is None:
            return
        r, c, age = self._last_action
        if age > 35:
            return
        alpha = int(255 * (1 - age / 35))
        hl    = self._tile.get("highlight")
        if hl:
            copy = hl.copy()
            copy.set_alpha(alpha)
            surf.blit(copy, (c * TILE_SIZE, r * TILE_SIZE))

    def _draw_ambient_layer(self, surf: pygame.Surface):
        for orb in self._ambient_orbs:
            orb.update()
            orb.draw(surf)

    def _tick_last_action(self):
        if self._last_action is not None:
            self._last_action[2] += 1
            if self._last_action[2] > 35:
                self._last_action = None

    def _apply_day_night(self, surf: pygame.Surface, world):
        phase = (getattr(world, "turn", 0) % 20) // 5
        r, g, b, a = DAY_TINTS[phase]
        if a == 0:
            return
        tint = pygame.Surface((GRID_PX_W, GRID_PX_H), pygame.SRCALPHA)
        tint.fill((r, g, b, a))
        surf.blit(tint, (0,0), special_flags=pygame.BLEND_RGBA_MULT
                  if a > 0 else 0)

    # ── PARTICLES & FLOATS ────────────────────────────────────────────────────

    def _update_and_draw_particles(self):
        alive = []
        for p in self._particles:
            p.update()
            if p.alive:
                p.draw(self.screen)
                alive.append(p)
        self._particles = alive

    def _update_and_draw_floats(self):
        alive = []
        for f in self._floats:
            f.update()
            if f.alive:
                f.draw(self.screen, self.font_md)
                alive.append(f)
        self._floats = alive

    # ── UI PANEL ──────────────────────────────────────────────────────────────

    def _draw_ui_panel(self, world):
        px = UI_PANEL_X
        pw = UI_PANEL_WIDTH
        ph = SCREEN_HEIGHT

        # Panel background
        pygame.draw.rect(self.screen, C_PANEL, (px, 0, pw, ph))
        # Header bar
        pygame.draw.rect(self.screen, C_PANEL_DARK, (px, 0, pw, 54))
        # Left border accent
        pygame.draw.rect(self.screen, C_ACCENT, (px, 0, 2, ph))

        x  = px + 16
        y  = 10
        uw = pw - 32

        # ── Title ──
        title = self.font_lg.render("WORLD BALANCE", True, C_TEXT_BRIGHT)
        self.screen.blit(title, (x, y))
        y += 24
        sub = self.font_xs.render("A R C H I T E C T S", True, C_ACCENT)
        self.screen.blit(sub, (x + 2, y))
        y += 24

        self._divider(x, y, uw); y += 10

        # ── Planet Meters ──
        label_h = self.font_xs.render("PLANETARY STATUS", True, C_TEXT_DIM)
        self.screen.blit(label_h, (x, y)); y += 14

        meters = [
            ("WATER",  getattr(world, "water_level", 50),  METER_COLORS["water"]),
            ("FOOD",   getattr(world, "food",         50),  METER_COLORS["food"]),
            ("OXYGEN", getattr(world, "oxygen",        50),  METER_COLORS["oxygen"]),
            ("TEMP",   getattr(world, "temperature",   50),  METER_COLORS["temp"]),
        ]
        for label, value, color in meters:
            y = self._draw_meter(x, y, uw, label, float(value), color)
            y += 5

        self._divider(x, y, uw); y += 10

        # ── Stability ──
        stab = getattr(world, "stability", 0.5)
        stab_col = self._stability_color(stab)
        sl = self.font_xs.render("STABILITY", True, C_TEXT_DIM)
        sv = self.font_md.render(f"{stab:.2f}", True, stab_col)
        self.screen.blit(sl, (x, y))
        self.screen.blit(sv, (x + uw - sv.get_width(), y - 1))
        y += 18
        # Stability bar
        self._draw_bar(x, y, uw, 12, stab, stab_col, bg=(25,30,50))
        y += 20

        self._divider(x, y, uw); y += 10

        # ── Turn info ──
        turn = getattr(world, "turn", 0)
        tl   = self.font_sm.render(f"TURN  {turn} / {MAX_TURNS}", True, C_TEXT)
        self.screen.blit(tl, (x, y)); y += 20

        cur_agent = getattr(world, "current_agent", AGENT_A)
        ac        = AGENT_A_COLOR if cur_agent == AGENT_A else AGENT_B_COLOR
        atl       = self.font_sm.render(f"ACTIVE: Agent {cur_agent}", True, ac)
        self.screen.blit(atl, (x, y))
        if self._thinking_agent:
            self._draw_thinking_dot(x + uw - 18, y + 6, ac)
        y += 22

        self._divider(x, y, uw); y += 10

        # ── Scores ──
        scores = getattr(world, "scores", {AGENT_A: 0, AGENT_B: 0})
        eco    = getattr(world, "eco_points", {AGENT_A: 10, AGENT_B: 10})
        sc_l   = self.font_xs.render("SCORES", True, C_TEXT_DIM)
        self.screen.blit(sc_l, (x, y)); y += 14

        for agent, color in [(AGENT_A, AGENT_A_COLOR),(AGENT_B, AGENT_B_COLOR)]:
            max_score = max((*scores.values(), 1))
            bar_w = int(uw * min(1.0, scores.get(agent,0) / max_score))
            # Score bar background
            pygame.draw.rect(self.screen, (30,35,55), (x, y, uw, 18), border_radius=3)
            if bar_w > 0:
                pygame.draw.rect(self.screen, (*color, 180), (x, y, bar_w, 18), border_radius=3)
            name_s = self.font_sm.render(f"Agent {agent}", True, C_TEXT_BRIGHT)
            val_s  = self.font_sm.render(f"{scores.get(agent,0):.1f}", True, C_TEXT_BRIGHT)
            eco_s  = self.font_xs.render(f"eco:{eco.get(agent,0)}", True, C_TEXT_DIM)
            self.screen.blit(name_s, (x + 5, y + 1))
            self.screen.blit(val_s,  (x + uw - val_s.get_width() - 5, y + 1))
            self.screen.blit(eco_s,  (x + 5, y + 20))
            y += 38

        self._divider(x, y, uw); y += 10

        # ── Action Log ──
        log_l = self.font_xs.render("ACTION LOG", True, C_TEXT_DIM)
        self.screen.blit(log_l, (x, y)); y += 14
        log   = getattr(world, "action_log", [])
        for i, entry in enumerate(log[-7:]):
            # Alternate slightly different brightnesses
            shade = C_TEXT if i == len(log[-7:])-1 else C_TEXT_DIM
            line  = self.font_xs.render(entry[:36], True, shade)
            self.screen.blit(line, (x, y)); y += 15

        # ── Legend ──
        if y < SCREEN_HEIGHT - 100:
            y = SCREEN_HEIGHT - 100
            self._divider(x, y, uw); y += 8
            legend = [
                (TERRAIN_LAND,       "Land"),
                (TERRAIN_RIVER,      "River"),
                (TERRAIN_FARM,       "Farm"),
                (TERRAIN_FOREST,     "Forest"),
                (TERRAIN_RESERVOIR,  "Reservoir"),
                (TERRAIN_SOLAR,      "Solar"),
            ]
            legend_x = x
            for terrain, name in legend:
                tile = self._tile.get(terrain)
                if tile:
                    sm = pygame.transform.scale(tile, (14,14))
                    self.screen.blit(sm, (legend_x, y))
                lbl = self.font_xs.render(name, True, C_TEXT_DIM)
                self.screen.blit(lbl, (legend_x + 17, y + 1))
                legend_x += lbl.get_width() + 26
                if legend_x > px + pw - 40:
                    legend_x = x
                    y += 18

    # ── GAME OVER OVERLAY ─────────────────────────────────────────────────────

    def _draw_gameover_overlay(self, world, winner: str):
        # Full-screen dim
        dim = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        dim.fill((0, 0, 0, 175))
        self.screen.blit(dim, (0, 0))

        cx = GRID_PX_W // 2
        cy = SCREEN_HEIGHT // 2

        # Glow box
        box_w, box_h = 480, 200
        box = pygame.Surface((box_w, box_h), pygame.SRCALPHA)
        pygame.draw.rect(box, (20, 24, 40, 230), (0,0,box_w,box_h), border_radius=12)
        pygame.draw.rect(box, C_GOLD + (200,),  (0,0,box_w,box_h), 2, border_radius=12)
        self.screen.blit(box, (cx - box_w//2, cy - box_h//2))

        # Winner text
        win_t = self.font_xl.render(f"AGENT {winner} WINS", True, C_GOLD)
        self.screen.blit(win_t, win_t.get_rect(center=(cx, cy - 60)))

        # Stability
        stab   = getattr(world, "stability", 0.5)
        stab_c = self._stability_color(stab)
        st_t   = self.font_md.render(f"Final Stability: {stab:.2f}", True, stab_c)
        self.screen.blit(st_t, st_t.get_rect(center=(cx, cy - 20)))

        # Scores
        scores = getattr(world, "scores", {AGENT_A: 0, AGENT_B: 0})
        for i, (agent, color) in enumerate([(AGENT_A,AGENT_A_COLOR),(AGENT_B,AGENT_B_COLOR)]):
            s = self.font_md.render(
                f"Agent {agent}: {scores.get(agent,0):.1f}", True, color)
            self.screen.blit(s, s.get_rect(center=(cx + (i*2-1)*100, cy + 20)))

        restart = self.font_sm.render("Press R to restart  /  ESC to quit",
                                      True, C_TEXT_DIM)
        self.screen.blit(restart, restart.get_rect(center=(cx, cy + 60)))

    # ── WIDGET HELPERS ────────────────────────────────────────────────────────

    def _draw_meter(self, x:int, y:int, width:int,
                    label:str, value:float, color:tuple) -> int:
        # Flash animation when critical
        is_critical = value < 20
        draw_color  = color
        if is_critical:
            t = (math.sin(self._ticks * 0.18) + 1) * 0.5
            draw_color = (
                int(color[0]*(1-t) + 220*t),
                int(color[1]*(1-t) +  40*t),
                int(color[2]*(1-t) +  40*t),
            )

        # Label row
        lbl = self.font_xs.render(label, True, C_TEXT_DIM)
        val = self.font_xs.render(
            f"{'⚠ ' if is_critical else ''}{value:.1f}", True, draw_color)
        self.screen.blit(lbl, (x, y))
        self.screen.blit(val, (x + width - val.get_width(), y))
        y += 14

        self._draw_bar(x, y, width, 8, value / 100.0, draw_color)
        return y + 8

    def _draw_bar(self, x:int, y:int, w:int, h:int,
                  ratio:float, color:tuple, bg=(30,35,55)):
        ratio = max(0.0, min(1.0, ratio))
        pygame.draw.rect(self.screen, bg,    (x, y, w, h), border_radius=h//2)
        fw = int(w * ratio)
        if fw > 0:
            pygame.draw.rect(self.screen, color, (x, y, fw, h), border_radius=h//2)
            # Bright tip pixel
            if fw > 3:
                bright = tuple(min(255, c+80) for c in color)
                pygame.draw.rect(self.screen, bright, (x+fw-3, y+1, 3, h-2),
                                 border_radius=2)

    def _draw_thinking_dot(self, x:int, y:int, color:tuple):
        t = (math.sin(self._ticks * 0.14) + 1) * 0.5
        r = int(4 + 2 * t)
        s = pygame.Surface((r*2+2, r*2+2), pygame.SRCALPHA)
        pygame.draw.circle(s, (*color, 200), (r+1,r+1), r)
        self.screen.blit(s, (x - r, y - r))

    def _divider(self, x:int, y:int, w:int):
        pygame.draw.line(self.screen, C_BORDER, (x, y), (x+w, y))

    @staticmethod
    def _stability_color(stab: float) -> tuple:
        if stab >= STABILITY_HIGH:     return C_GOOD
        elif stab >= STABILITY_MODERATE: return C_WARN
        elif stab >= STABILITY_LOW:    return (220, 130, 40)
        else:                          return C_DANGER

    # ── CONVENIENCE: spawn action FX from outside ─────────────────────────────

    ACTION_FX = {
        "harvest_crop":   ("+Food",   (180, 240,  80), (100, 200,  60)),
        "plant_forest":   ("+O₂",     ( 80, 230, 140), ( 40, 180,  80)),
        "plant_crop":     ("Planted", (140, 220,  80), ( 80, 160,  40)),
        "build_canal":    ("+Water",  (100, 190, 255), ( 40, 120, 200)),
        "build_solar":    ("+Energy", (255, 220,  80), (200, 160,  40)),
        "plant_reservoir":("+Water",  ( 80, 160, 240), ( 40, 100, 190)),
        "clear_forest":   ("-O₂",     (255, 100,  60), (180,  40,  20)),
    }

    def trigger_action_fx(self, action_name: str, col: int, row: int):
        """Spawn FloatingText + particles matching the action type."""
        fx = self.ACTION_FX.get(action_name)
        if fx:
            text, text_color, particle_color = fx
            self.add_float(text, col, row, text_color)
            self.add_particles(col, row, particle_color, count=10)
            self.set_last_action(row, col)
